### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by happyday22** [UCLA-VAST/splag#1]
Hello, we tried to run your program. We have successfully installed TAPA and Autobridge. However, when compiling your project, TAPA cannot be found, and the error is as shown in the figure below.
![1 (2)](https://user-images.githubusercontent.com/30362615/174473096-1209a99d-3707-4cf0-99d7-cdac3af1e450.png)

**Comment by Blaok** [comment]
Hi @happyday22, TAPA has evolved significantly after SPLAG was created. The best way to reproduce the results is to use the [Dockerfile](https://github.com/UCLA-VAST/splag/blob/master/docker/Dockerfile), which has pinned the versions of most dependencies.

As for the error you encountered, most likely it is because TAPA was not installed correctly. Could you check if `/usr/lib/cmake/tapa/TAPAConfig.cmake` exists? TAPA is not designed nor tested to work with `-DCMAKE_MODULE_PATH=`.

**Comment by happyday22** [comment]
We try to modify it according to your method, but there will still be other errors. Could you provide the dockerfile if it is convenient for you?

**Comment by Blaok** [comment]
Oh, I didn't notice the link was broken. The dockerfile is https://github.com/UCLA-VAST/splag/blob/master/docker/Dockerfile.

**Comment by happyday22** [comment]
Thank you for your reply.
